theme: jekyll-theme-cayman
title: [Shaun J. Cameron]
description: [Welcome to the site of Shaun J. Cameron. On this site you can find documentation for Projects, programming Examples and possibly a blog!]
