<<<<<<< HEAD
theme: jekyll-theme-tactile
title: Quentin 'Q' J. Thomas
=======
theme: jekyll-theme-tactile
title: Quentin 'Q' J. Thomas
>>>>>>> 1bc3289da423a8ef3fed0521f6cb468dcd30f4ba
description: “Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live” - John Woods, 1991
